version: '2'
services:
  mydt:
    image: "mcchae/vbuntu-pyenv"
    hostname: "mydt"
    ports:
      - "33898:3389"
    volumes:
      - ${HOME}/dhv/vbuntu/root:/root
      - ${HOME}/work:/root/work

